### ISSUE TITLE
buildozer file missing???

### ISSUE THREAD

**Issue by robotixdevteam** [JaisonJose241/driverlessCAR#1]
nice work man.... Can you provide buildozer for this process? is this two app controller and autonomous???

**Comment by JaisonJose241** [comment]
its one app controller, and works via OTG.
sry i don't have the buildozer file, btw u cn generate it.
and yeah its autonomous.

can i know what are you guys working on?

**Comment by robotixdevteam** [comment]
we are working on driverless cars using products like raspberry, arduino and jetson nano.
